# PBS configuration

# If submitting to a different project to your default, uncomment line below
# and change project code as appropriate; also set shortpath below
project: x77

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
shortpath: /scratch/x77

queue: normal
ncpus: 216
walltime: 3:00:00
jobname: flux_forced
# mem: 1000GB

# Model configuration
# name: common
model: mom
#    - name: ocean
exe: /scratch/x77/db6174/MoM5/exec/nci/MOM_solo/fms_MOM_solo.x
input: 
     - /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg
     - /scratch/x77/db6174/1deg_inputs/flux_forced_attempt1
     - /home/156/db6174/access-om2/1deg_jra55_ryf/1deg_jra55_ryf_flux_forced_attempt1/restart_file
     - /home/156/db6174
# Collation
collate:
  restart: true
  walltime: 1:00:00
  mem: 30GB
  ncpus: 4
  queue: normal
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

# Misc
runlog: true
stacksize: unlimited
restart_freq: 1  # use tidy_restarts.py instead
mpirun: --mca io ompio --mca io_ompio_num_aggregators 1
qsub_flags: -W umask=027
env:
    UCX_LOG_LEVEL: 'error'
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48
# sweep and resubmit on specific errors - see https://github.com/payu-org/payu/issues/241#issuecomment-610739771
# DANGER! Do not uncomment this without checking the script is syncing to the correct location!
# postscript: sync_data.sh
