format: yamanifest
version: 1.0
---
work/INPUT/chl.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/chl.nc
  hashes:
    binhash: 05b3313121bbb9825a20f0fb58901b21
    md5: a7aa5bcf4a3b9fa8102edd3b6b67c3a2
work/INPUT/evap.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/evap.nc
  hashes:
    binhash: a2bde02638dc9276c773bf8cf0be6096
    md5: 28b45e5b25558be325a45f56064b83a2
work/INPUT/evap_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/evap_new.nc
  hashes:
    binhash: 4d3157d58d6f02081e0a7348c4e39306
    md5: 20ff5c2e92f376d3e5d6c32ba423f4d6
work/INPUT/fprec.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/fprec.nc
  hashes:
    binhash: e98f839b9b5a44ebb6ee799d1ad614c9
    md5: 25bc04df82053cf14a88dd2b516bd38b
work/INPUT/fprec_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/fprec_new.nc
  hashes:
    binhash: 692ec4fd4f86b429c665432ce968cd20
    md5: b1b9c7077a3775b13be7dbc42c029988
work/INPUT/grid_spec.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/grid_spec.nc
  hashes:
    binhash: 587ca8eb0cbc978232fe55a7bff054c9
    md5: 027d2f8fb1eda3ef1cf0a3f520a217f7
work/INPUT/lprec.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/lprec.nc
  hashes:
    binhash: 5e90d7cb77df0ce5f69af8c53037aa90
    md5: 6c74e213192af0611301783e383786a8
work/INPUT/lprec_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/lprec_new.nc
  hashes:
    binhash: f2d872b8b962160eae9b388f6747d94e
    md5: b722d23ad2bdd17ae1e4f9f057210cc9
work/INPUT/lw_heat.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/lw_heat.nc
  hashes:
    binhash: a3603f0160a1bf5b4218a78cc6530bcc
    md5: 0e08f5ad009ce42218b51882d6558170
work/INPUT/lw_heat_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/lw_heat_new.nc
  hashes:
    binhash: 94cd40fd2136eab3d458346757ab20fc
    md5: c9775feb3a5d07e752451b86839f42f5
work/INPUT/mask_table.24.16x15:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/mask_table.24.16x15
  hashes:
    binhash: 77b929b930cd4fca59f185b3222dde49
    md5: 2203b38758fb2b56a145ef16b7872af9
work/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_hgrid.nc
  hashes:
    binhash: 87d66edc0ef57c97b758a3049bfe8a14
    md5: 51f58be0f4ea6da2cb438a893f95c689
work/INPUT/ocean_mask.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_mask.nc
  hashes:
    binhash: ab10098b71d76ba5fcf0ea9e007a90e5
    md5: 411567441c64bcfa814259736c5ed1a3
work/INPUT/ocean_mask_table:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_mask_table
  hashes:
    binhash: dc68931f1bb40bcd75a98d209b47d4c4
    md5: 2203b38758fb2b56a145ef16b7872af9
work/INPUT/ocean_mosaic.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_mosaic.nc
  hashes:
    binhash: 6aadd388078defe3f80df6f3de77b4bd
    md5: cb42e630ee31d3686156fcbdc2f9d07c
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_temp_salt.res.nc
  hashes:
    binhash: 1530c856cbbc9b5073bdf3e7beb72cd7
    md5: c5f7e60b5427a4442f111adc65a2d067
work/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_vgrid.nc
  hashes:
    binhash: cd9ef67b8cf6d4ea0c78554ac38e1bc3
    md5: 339ff716e3019a86fc861498e674250a
work/INPUT/roughness_amp.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/roughness_amp.nc
  hashes:
    binhash: 73a425be9e5cf7a3d349d75a8ebeadd1
    md5: 185dadeb53da2de75b47c53fd7085f89
work/INPUT/roughness_cdbot.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/roughness_cdbot.nc
  hashes:
    binhash: 4ec236c3874fbd4dc5c2fcdec271f557
    md5: b50f0595f3ebc872cbcf5f3223115643
work/INPUT/runoff.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/runoff.nc
  hashes:
    binhash: 9af115f424205adfcccdac4d9bad47f3
    md5: 459ea171041ba4dfcb580dbddc109d53
work/INPUT/runoff_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/runoff_new.nc
  hashes:
    binhash: 30cea5db6fcb23eb9000dabcbd926e04
    md5: 49aee4ae1b1cff9730faa855ad5c71ac
work/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/salt_sfc_restore.nc
  hashes:
    binhash: 13101e8424f559b6c172ef86d85b9a8f
    md5: b2bd35c44017597ba99b85fb61ed4d72
work/INPUT/sens_heat.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sens_heat.nc
  hashes:
    binhash: 950ba5ea20175167e9d1bab4b1ea5bb8
    md5: ffd6033fcb7add7f66a442149ff8a4c2
work/INPUT/sens_heat_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sens_heat_new.nc
  hashes:
    binhash: 066d93c685e37bb3b16513bca47b0aa4
    md5: 3a576597dc807d0338b3a9d6c3986fca
work/INPUT/sfc_salt_flux_coupler.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sfc_salt_flux_coupler.nc
  hashes:
    binhash: d17dcb1bcf83defae31768cac4845e9b
    md5: 21a57411a64178c84709e5de04955e2e
work/INPUT/sfc_salt_flux_coupler_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sfc_salt_flux_coupler_new.nc
  hashes:
    binhash: 7ef65ad22f28005f5d2b35c904012ff9
    md5: 05630ac4156464803ad8ece15040eb89
work/INPUT/sw_flux_nir_dif.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sw_flux_nir_dif.nc
  hashes:
    binhash: f871a32d7833336d5785187346f606b6
    md5: 058ce35d53336c65e9017b0faa285162
work/INPUT/sw_flux_nir_dif_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sw_flux_nir_dif_new.nc
  hashes:
    binhash: 434f6720c6f39642a4d5cf4b7656cf04
    md5: 5b6ab8091af99ef8f4e0bc276053116a
work/INPUT/sw_flux_nir_dir.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sw_flux_nir_dir.nc
  hashes:
    binhash: 17396c775a9782aaaa1032690688f195
    md5: 0b57c42c41f0fb3ca70b0f1c7f196bd2
work/INPUT/sw_flux_nir_dir_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sw_flux_nir_dir_new.nc
  hashes:
    binhash: 225c325b5d75a6006482dbb72f78212c
    md5: 0ad621dab292b18598c9c9d04b0edb8a
work/INPUT/sw_flux_vis_dif.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sw_flux_vis_dif.nc
  hashes:
    binhash: c8997287c0e046e2720c776da2866a14
    md5: 15802731a441e551d5fee49ddacecd39
work/INPUT/sw_flux_vis_dif_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sw_flux_vis_dif_new.nc
  hashes:
    binhash: 4d1f97387675977933857c4fcecc77e6
    md5: e77f5150dded20d9aed21670862ab75e
work/INPUT/sw_flux_vis_dir.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sw_flux_vis_dir.nc
  hashes:
    binhash: 42ef7cfebc91a4c56280ddc730dbcca2
    md5: 03cc05471aa01f4032054d663b86a7b7
work/INPUT/sw_flux_vis_dir_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/sw_flux_vis_dir_new.nc
  hashes:
    binhash: 9184f9d93cb50152a7edea6ffe39d787
    md5: 429d97b1bbd3e8546e583c24b0d2a074
work/INPUT/tau_x.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/tau_x.nc
  hashes:
    binhash: be2dc97da67ba49032997d7fb8f74d09
    md5: 821eef498a825951df0a432ed1c01bde
work/INPUT/tau_x_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/tau_x_new.nc
  hashes:
    binhash: 2cc31261e1aec3c08a69ed8a6a3b80e5
    md5: dfe89a855a7d07a41bfd2b2f0096e4a8
work/INPUT/tau_y.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/tau_y.nc
  hashes:
    binhash: 030c18418243feb31bc9da020f2bc284
    md5: 621f4faf7833b26738be50fd36f35896
work/INPUT/tau_y_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_diurnal/tau_y_new.nc
  hashes:
    binhash: 51fd140319ac2623aff2939fc79eafb5
    md5: 1ad7ef43cc1cb62337b7e1304d96df5d
work/INPUT/tideamp.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/tideamp.nc
  hashes:
    binhash: 0226a494f8a03f8fb9845060cb694389
    md5: b2840af757d9b7b40207f33f1fc84c5c
work/INPUT/topog.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/topog.nc
  hashes:
    binhash: 8ab65e521a588943b533b188a619d361
    md5: 4e13d88001b646f3cf4f1c3b8db59f91
