format: yamanifest
version: 1.0
---
work/INPUT/chl.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/chl.nc
  hashes:
    binhash: 05b3313121bbb9825a20f0fb58901b21
    md5: a7aa5bcf4a3b9fa8102edd3b6b67c3a2
work/INPUT/evap.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/evap.nc
  hashes:
    binhash: e94e8abfb736839d4447bbdd04c2758a
    md5: ef51796f52e2747f96c5c5c59665bcb9
work/INPUT/evap_heat.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/evap_heat.nc
  hashes:
    binhash: f1ebb80a01c87b1c15085b51b5e501f7
    md5: 981e2754dfb7b5cda22ca80b5d08d02e
work/INPUT/evap_heat_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/evap_heat_new.nc
  hashes:
    binhash: 5e5712e03422215f03ad13cce6054b6f
    md5: 0dd836b58f0acca0124180ab493fdcc2
work/INPUT/evap_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/evap_new.nc
  hashes:
    binhash: a4b4982d6b25f90a430a51d93debf71d
    md5: a07ce33264cd7a593c37a5883671c2e7
work/INPUT/fprec.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/fprec.nc
  hashes:
    binhash: cf9503cad60b8c05e326780dd0a5421d
    md5: 35d920b96276176f35132aaabb2d0d19
work/INPUT/fprec_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/fprec_new.nc
  hashes:
    binhash: d3cc002b784170f5759a78866b64c49e
    md5: dd0b9b754494064b2c0c6b5d0cf8b4cb
work/INPUT/grid_spec.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/grid_spec.nc
  hashes:
    binhash: 587ca8eb0cbc978232fe55a7bff054c9
    md5: 027d2f8fb1eda3ef1cf0a3f520a217f7
work/INPUT/lprec.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/lprec.nc
  hashes:
    binhash: ebe06cfe5fd56580aa00576f01921add
    md5: 5bac831d48ab32eeb0f9eefa643ed518
work/INPUT/lprec_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/lprec_new.nc
  hashes:
    binhash: 70e2f810b3367a8c97377b4489e409df
    md5: d37aea9a5aed9010fd5e385939df9ae2
work/INPUT/lw_heat.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/lw_heat.nc
  hashes:
    binhash: 686e16a5ffed55d1db29da530c0dee0b
    md5: e79e76bb1d336ce50c75372d3b710ba5
work/INPUT/lw_heat_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/lw_heat_new.nc
  hashes:
    binhash: 5ce213ba5c425b688e32401f4467e29b
    md5: 091cd57f82fd9357444b58913871959f
work/INPUT/mask_table.24.16x15:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/mask_table.24.16x15
  hashes:
    binhash: 77b929b930cd4fca59f185b3222dde49
    md5: 2203b38758fb2b56a145ef16b7872af9
work/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_hgrid.nc
  hashes:
    binhash: 87d66edc0ef57c97b758a3049bfe8a14
    md5: 51f58be0f4ea6da2cb438a893f95c689
work/INPUT/ocean_mask.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_mask.nc
  hashes:
    binhash: ab10098b71d76ba5fcf0ea9e007a90e5
    md5: 411567441c64bcfa814259736c5ed1a3
work/INPUT/ocean_mask_table:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_mask_table
  hashes:
    binhash: dc68931f1bb40bcd75a98d209b47d4c4
    md5: 2203b38758fb2b56a145ef16b7872af9
work/INPUT/ocean_mosaic.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_mosaic.nc
  hashes:
    binhash: 6aadd388078defe3f80df6f3de77b4bd
    md5: cb42e630ee31d3686156fcbdc2f9d07c
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_temp_salt.res.nc
  hashes:
    binhash: 1530c856cbbc9b5073bdf3e7beb72cd7
    md5: c5f7e60b5427a4442f111adc65a2d067
work/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/ocean_vgrid.nc
  hashes:
    binhash: cd9ef67b8cf6d4ea0c78554ac38e1bc3
    md5: 339ff716e3019a86fc861498e674250a
work/INPUT/patm_t.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/patm_t.nc
  hashes:
    binhash: e5a2f8db9b118439b7667875739cd9b6
    md5: 2b1e14edb4a5bfc9060684d2268dd888
work/INPUT/patm_t_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/patm_t_new.nc
  hashes:
    binhash: 8d17bc36724feb5c561009d3accbca24
    md5: f0bce28488277b8c2a059e5dfe2226e0
work/INPUT/roughness_amp.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/roughness_amp.nc
  hashes:
    binhash: 73a425be9e5cf7a3d349d75a8ebeadd1
    md5: 185dadeb53da2de75b47c53fd7085f89
work/INPUT/roughness_cdbot.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/roughness_cdbot.nc
  hashes:
    binhash: 4ec236c3874fbd4dc5c2fcdec271f557
    md5: b50f0595f3ebc872cbcf5f3223115643
work/INPUT/runoff.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/runoff.nc
  hashes:
    binhash: 6ed848d2ff4512597d2e527fbde415dc
    md5: 14388dd6ab5894a5e84a1aabcec7c143
work/INPUT/runoff_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/runoff_new.nc
  hashes:
    binhash: a729a7c09523bd8ab9d9495943e8624d
    md5: bb33cd44b59a353555b7989722d70699
work/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/salt_sfc_restore.nc
  hashes:
    binhash: 13101e8424f559b6c172ef86d85b9a8f
    md5: b2bd35c44017597ba99b85fb61ed4d72
work/INPUT/sens_heat.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sens_heat.nc
  hashes:
    binhash: 5722933d3a7d5394d69a10ff3385e562
    md5: 3bfd11eb33e8f147d5345d3a9f983658
work/INPUT/sens_heat_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sens_heat_new.nc
  hashes:
    binhash: cbb880246b001a85018f10519d215ef0
    md5: 8c44ec34170eed8904acfb36679653ff
work/INPUT/sfc_salt_flux_coupler.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sfc_salt_flux_coupler.nc
  hashes:
    binhash: 8ea1c84d8311ea4e328893f947474f59
    md5: f192f3129153a4d22d8989d98559b3f7
work/INPUT/sfc_salt_flux_coupler_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sfc_salt_flux_coupler_new.nc
  hashes:
    binhash: c242400dac3311f86def73e1b6f36192
    md5: ccd1aa5f7805fddef9aa3a32704a770e
work/INPUT/sw_flux_nir_dif.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sw_flux_nir_dif.nc
  hashes:
    binhash: 0ddffde652c0538ab126361eb7cd412f
    md5: e92c8fba258a973314ebd1035878793e
work/INPUT/sw_flux_nir_dif_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sw_flux_nir_dif_new.nc
  hashes:
    binhash: ab52549d96756cb5affbd51f10d7e88d
    md5: 181d9a54fd6877b7674f9997224d5939
work/INPUT/sw_flux_nir_dir.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sw_flux_nir_dir.nc
  hashes:
    binhash: 3b5feee175b67ec2a46f8268e5bffedf
    md5: d8da3a5d70e3e92c381e79d9850b9589
work/INPUT/sw_flux_nir_dir_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sw_flux_nir_dir_new.nc
  hashes:
    binhash: 832cc38e681ea8240ebf5c57244873cd
    md5: 13da552893081b160cee0026afb20223
work/INPUT/sw_flux_vis_dif.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sw_flux_vis_dif.nc
  hashes:
    binhash: 130f7c5eb03608599f5c31f81405c233
    md5: 52dd49e81ca73c50701d989a10800d2d
work/INPUT/sw_flux_vis_dif_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sw_flux_vis_dif_new.nc
  hashes:
    binhash: 72c8da77424d35cc23aa166222005c7b
    md5: edb582240d905e3883b7109dc4a8d18d
work/INPUT/sw_flux_vis_dir.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sw_flux_vis_dir.nc
  hashes:
    binhash: 556492a8b1e3c3c8ceca6c10191349b6
    md5: 5ff8a905ac0b601d7e48dcc68f950560
work/INPUT/sw_flux_vis_dir_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/sw_flux_vis_dir_new.nc
  hashes:
    binhash: b4c0b4e628056a70a837cd7dfa68eea1
    md5: 74009aac9eae1d648fa21c954f32be2b
work/INPUT/tau_x.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/tau_x.nc
  hashes:
    binhash: 0b105a6713e2d62937112105aeb99533
    md5: fc7dbca7773cc580070acc6a5c9de383
work/INPUT/tau_x_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/tau_x_new.nc
  hashes:
    binhash: 47be4845b3aedcbac1bf3d6350d3b103
    md5: 609fb42db4c67f79bd4733937aa681bb
work/INPUT/tau_y.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/tau_y.nc
  hashes:
    binhash: 4e6d1fd1eb93e4a6cb6faa08fd262e42
    md5: 7bce378c0078bd3c11c54b3959a3570d
work/INPUT/tau_y_new.nc:
  fullpath: /scratch/x77/db6174/1deg_inputs/flux_forced_with_mhflux/tau_y_new.nc
  hashes:
    binhash: 1d4f5291e5601dfc6a9674d463e6f086
    md5: 45a48072543302315b02439c5a296333
work/INPUT/tideamp.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/tideamp.nc
  hashes:
    binhash: 0226a494f8a03f8fb9845060cb694389
    md5: b2840af757d9b7b40207f33f1fc84c5c
work/INPUT/topog.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_1deg/topog.nc
  hashes:
    binhash: 8ab65e521a588943b533b188a619d361
    md5: 4e13d88001b646f3cf4f1c3b8db59f91
